apiVersion: v1
kind: Service
metadata:
  name: my-java-app
spec:
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 80  # The port you want to access
      targetPort: 8080  # The container port
  type: NodePort  # Use NodePort if using Minikube

